### ISSUE TITLE
AKS Intro Hack: 07-updaterollback.md has incorrect date for v2 of website

### ISSUE THREAD

**Issue by mattfeltonma** [microsoft/WhatTheHack#202]
The version 2 of content-web provides the conference date of 2020 not 2019. This should be corrected in the student instructions.

**Comment by larryclaman** [comment]
Just adding context to this issue:  With V2 of the app, when you are on the home page, it shows the date: 'FEBRUARY 14-17, 2020', but when you go to /sessions or /speakers, it shows the date 'FEBRUARY 14-17, 2019'.

This requires a simple correction to the the file \Student\Resources\Challenge 7\content-web-v2\public\index.html, but we'd also need to rebuild the docker image stored on dockerhub.
