### ISSUE TITLE
MDW Hacks Should have Purview

### ISSUE THREAD

**Issue by JoshLuedeman** [microsoft/WhatTheHack#303]
Each hack that is an MDW, or some variation of it, should include a challenge for deploying Purview as part of the solution, and another step after implemented, a challenge on applying classifications or creating a business glossary.

**Comment by jrzyshr** [comment]
Hi @JoshLuedeman, Thanks for your suggestion here.  We have two hacks that cover MDW.  019-ThisOldDataWarehouse (https://github.com/microsoft/WhatTheHack/tree/master/019-ThisOldDataWarehouse) & 038-MDWCovid19 (https://github.com/microsoft/WhatTheHack/tree/master/038-MDWCovid19).

I'm tagging @DataSciNAll & @blevinscm as they are the original authors of these two hacks for their input.

A new PR appeared shortly after you submitted this issue with a proposal for a new hack solely on Purview by Situmali Chandra Mohan. Is that something you are working with Situmali on?

**Comment by JoshLuedeman** [comment]
I was not but can I follow up with him and see about joining forces.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jrzyshr** [comment]
@JoshLuedeman Situmali is on vacation until 11/21.  I'll reach out to connect you when he returns.

**Comment by JoshLuedeman** [comment]
Not a problem. We’re connected. I’ll reach out when he returns

**Comment by JoshLuedeman** [comment]
I’m going to close this issue. Thank you
