### ISSUE TITLE
Implement Issue templates for the new Issue types we will use to better enable contributor engagement with the WTH team

### ISSUE THREAD

**Issue by jrzyshr** [microsoft/WhatTheHack#310]
The primary way to engage and get in touch with the What The Hack team will be to submit an issue via Github. This section describes the guidelines for submitting issues.

Issue Types
There are 5 types of issues:

Issue/Bug: You've found a bug in a hack and want to report it, create an issue to track the bug.
Issue/Discussion: You have a suggestion on how to improve an existing hack.
Issue/Proposal: Used to propose a new hack. This will get the What The Hack team to engage with you and plug you into our contribution process.
Issue/Request: Want help hosting a WTH event? WTH content is self-serve, but we're happy to meet with you and walk you through how to do it.
Issue/Report: Want to share with us that you hosted a WTH event? We'd love to know how and where WTH content is being used. Give us your feedback, and let us know!

**Comment by plzm** [comment]
Done!
