### ISSUE TITLE
[Bug]: current version of pmdarima does not work

### ISSUE THREAD

**Issue by vivanwin** [microsoft/WhatTheHack#320]
### Which Hack?

032-MLOpsFromScratch

### Current Behavior

When using the most recent version of `pmdarima` you will get the below error:

Traceback (most recent call last):
  File "training/transactions_arima.py", line 67, in <module>
    model = ARIMA(train, order=(2,0,2))
  File "C:\Users\vivanwin\AppData\Local\Programs\Python\Python37\lib\site-packages\statsmodels\tsa\arima_model.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\vivanwin\AppData\Local\Programs\Python\Python37\lib\site-packages\statsmodels\tsa\arima_model.py", line 29, in __init__
    raise NotImplementedError(ARIMA_DEPRECATION_ERROR)
NotImplementedError: 
statsmodels.tsa.arima_model.ARMA and statsmodels.tsa.arima_model.ARIMA have
been removed in favor of statsmodels.tsa.arima.model.ARIMA (note the .
between arima and model) and statsmodels.tsa.SARIMAX.

### Expected Behavior

The model would be trained correctly.

### Environment

**OS**: win 11
**Python**: 3.7.3
**pmdarima**: 1.8.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShivaKumarChittamuru** [comment]
Thanks for reporting the issue, Vincent. Looks like we need to standardize a version of pmdarima that works with the dependencies. Since we are not using pmdarima in the hack anyway, we will just remove it from requirements.txt in the environment_setup to resolve this issue.
