### ISSUE TITLE
[Proposal]: Introduction to Azure RedHat Openshift (ARO)

### ISSUE THREAD

**Issue by toklive** [microsoft/WhatTheHack#328]
### Topic

A challenge-based training content to learn about Azure Red Hat OpenShift.

Azure Red Hat OpenShift provides highly available, fully managed OpenShift clusters on-demand, monitored and operated jointly by Microsoft and Red Hat. Kubernetes is at the core of Red Hat OpenShift. OpenShift brings added-value features to complement Kubernetes, making it a turnkey container platform as a service (PaaS) with a significantly improved developer and operator experience.

https://azure.microsoft.com/en-us/services/openshift/#overview

### Abstract/Learning Objectives

At end of the training, attendees will get a hands-on experience with the below topics,

- Setting up a basic ARO cluster
- Build and Deploy apps to ARO cluster
- Manage and monitor the apps on ARO cluster
- HA/DR with ARO cluster
- Securing ARO cluster

### Delivery Date

March 2022

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danielkon96** [comment]
Work on this has started. You can find all progress made on it here: https://github.com/danielkon96/WhatTheHack/tree/xxx-AzureRedHatOpenShift/xxx-AzureRedHatOpenShift

**Comment by sahandmohammadrehzaii** [comment]
hello poeple

**Comment by jrzyshr** [comment]
Congrats to the team on the publication of the Intro to Azure Red Hat OpenShift WTH!
