### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CHMAND** [microsoft/WhatTheHack#331]
### Which Hack?

003-DrivingMissData

### Current Behavior

Blob container with NY Taxi data is seemingly empty. SAS connection works, but storage explorer reports no data in blob container from link in challenge 2. 

This is the data location: https://pzpubliceus.blob.core.windows.net/nyctaxi?sv=2018-03-28&si=nyctaxi-public&sr=c&sig=f4%2ByhX8g9kngpufkftAgepsAt2WVC6D8xRLQEjjyF04%3D

### Expected Behavior

Would expect to find the data as described in the student guide. 

### Steps To Reproduce

Test SAS URL in Azure Storage Explorer 

### Anything else?

![DrivingMissData](https://user-images.githubusercontent.com/63638552/150747957-daf37a2d-c2e0-4b69-b4c2-3209885e2a85.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrzyshr** [comment]
Closing this issue as hack 003-DrivingMissData has been marked as "archived".  We welcome contributions from the community if anyone wants to update it.  Please open a Proposal issue as per the [WTH Contribution guide](https://aka.ms/wthcontribute) and the WTH team will help you get started.,
