### ISSUE TITLE
[Bug]: Taxi Data 404

### ISSUE THREAD

**Issue by scottroot2** [microsoft/WhatTheHack#366]
### Which Hack?

003-DrivingMissData

### Current Behavior

The Taxi data that is supposed to be located in https://pzpubliceus.blob.core.windows.net/nyctaxi?sv=2018-03-28&si=nyctaxi-public&sr=c&sig=f4%2ByhX8g9kngpufkftAgepsAt2WVC6D8xRLQEjjyF04%3D is not found.  

This hack can not be attempted without the taxi data available to the student.  

We did find alternative sources, but the author did some work to curate the data set ahead of time and the hack seems to depend on that work.

### Expected Behavior

The link should resolve to provide data for the hack.

### Steps To Reproduce

Open the word doc for Challenge02 and find the link for the taxi data.
Click the link.
404

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scottroot2** [comment]
I am not sure if this data source is the right one, but it seems to be what other relevant MSFT educational activities are using: https://azuresynapsestorage.blob.core.windows.net/sampledata/NYCTaxiSmall/NYCTripSmall.parquet

**Comment by jrzyshr** [comment]
Closing this issue as hack 003-DrivingMissData has been marked as archived. If anyone in the community wants to update it, we welcome contributions.  Reach out via a new Proposal issue and the WTH team will help you get started.
