### ISSUE TITLE
[Proposal]: Azure Chaos Studio

### ISSUE THREAD

**Issue by JerryMSFT** [microsoft/WhatTheHack#368]
### Topic

This intro level hack will help get you hands-on experience with Azure Chaos Studios. Chaos Engineering is a concept that comes from Netflix. Netflix’s video streaming platform is a “born in the cloud” application. As it is in the cloud, Netflix doesn’t have access to hardware and facilities, as such Netflix needed to to build and test resiliency in their streaming platform. Microsoft introduces Chaos Studio to measure, understand and how to improve service/workload resilience. Chaos Studio allows you to simulate region failure, VM and Networking issues.  

### Abstract/Learning Objectives

- This “What the Hack” WTH is designed to introduce you to Azure Chaos Studios and guide you through a series of hands-on challenges to accomplish the following:
    - Leverage the Azure Chaos Studio to inject failure into a workload
    - What is Chaos Engineering
    - What is the Well Architected Framework

### Delivery Date

May 1, 2020

### Authors

```markdown
JerryMSFT
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrzyshr** [comment]
#588 should close this issue.

**Comment by jrzyshr** [comment]
Congrats on publishing the new Chaos Studio for AKS hack!
