### ISSUE TITLE
[Proposal]: Azure Route Server

### ISSUE THREAD

**Issue by maurojasmsft** [microsoft/WhatTheHack#471]
### Topic

What the Hack on Azure Route Server

### Abstract/Learning Objectives

- BGP Review
- Understand how Azure Route Server leverages BGP to enable Dynamic Routing
- Understand Azure Route Server Route Exchange with Vnet Gateway
- Understand Azure Route Server Route Exchange with Vnet Gateway + On Prem
- Understand Azure Route Server routing exchange with Vnet Gateway + On Prem + NVA
- Understand  Azure Route Server with a hub and Spoke Topology 

### Delivery Date

Sep 30th

### Authors

```markdown
Jose Moreno @erjosito
Tsubasa Nomura
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrzyshr** [comment]
Thanks for the proposal!  I look forward to seeing this content contributed to the WTH project!

**Comment by jrzyshr** [comment]
This issue should be closed by PR #519
