### ISSUE TITLE
[Proposal]: New WhatTheHack covering Cosmos DB

### ISSUE THREAD

**Issue by istavrinides** [microsoft/WhatTheHack#480]
### Topic

This WTH will try to cover best practices in using Cosmos DB as both an operation backend and extending to Analytics. It will have challenges on Data Modeling and leveraging Cosmos DB features to solve interesting scenarios.

### Abstract/Learning Objectives

- Cosmos DB capacity options
- Cosmos DB data modeling and throughput, including troubleshooting a bad data model
- Cosmos DB monitoring
- Usage of features such as Change Feed, Synapse Link, Hierarchical Partition Keys, Partition merging and more

### Delivery Date

September 2022

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrzyshr** [comment]
Thanks @istavrinides for volunteering to create a new hack on Cosmos DB!  We look forward to adding it to the WTH collection soon!

**Comment by jrzyshr** [comment]
This Issue is closed by PR #507
