### ISSUE TITLE
[Proposal]: Update 007-AzureMonitoring hack

### ISSUE THREAD

**Issue by jrzyshr** [microsoft/WhatTheHack#495]
### Topic

Azure Monitoring

### Abstract/Learning Objectives

This will be a complete refresh to the existing 007-AzureMonitoring What The Hack.

The Azure Monitoring v2.0 What the Hack (WTH) provides hands on experience on how to monitor Azure workloads using Azure Monitor, Log Analytics, Insights, Workbooks and Grafana. This hack was designed specifically for Infrastructure engineers, DevOps engineers, administrators and IT architects who want to build their knowledge on Azure Monitor. However, anyone with a passion around Monitoring is welcome!

In this hack, you will be getting hands on experience with monitoring resources (VMs, applications, containers) using Azure Monitoring capabilities such as log analytics, dashboards, and KQL. Additionally, Grafana has been introduced to add additional visualization tools.

### Delivery Date

10/01/2022

### Authors

```markdown
Sherri Babylon, Peter Laudati
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WKahnZA** [comment]
@jrzyshr @shbabylo hi, I'd like to check if there's an update on this, I was about to update this hack myself and would rather collaborate towards this updated experience.

**Comment by jrzyshr** [comment]
Update... This hack refresh is still in progress.

**Comment by jrzyshr** [comment]
Great news!  The hack refresh has been submitted!   PR #717 should close this Issue

**Comment by jrzyshr** [comment]
Azure Monitoring hack refresh has now been published!
