### ISSUE TITLE
[Suggestion]: azuremonitor setup script still uses azureRM not AZ

### ISSUE THREAD

**Issue by WKahnZA** [microsoft/WhatTheHack#516]
### Which Hack?

007-AzureMonitoring

### Suggestion

[Suggestion]: azuremonitor setup script still uses azureRM not AZ

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrzyshr** [comment]
Closing this issue as it will be addressed in the upcoming Azure Monitoring hack refresh.
