### ISSUE TITLE
Issues found in Terraform

### ISSUE THREAD

**Issue by lastcoolnameleft** [microsoft/WhatTheHack#52]
1. Each of the terraform modules need to have the tags changed from 
```
tags { ... }
```
to 
```
tags = { ... }
```

This creates an error:
```
  on what-the-hack.tf line 11, in resource "azurerm_virtual_network" "myterraformnetwork":
  11:     tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.
```

For Challenge 4, you will also need to run `terraform plan -var-file variables.tfvars`.  It would be helpful if these commands were listed in the Solutions document.

For Challenge 5, you will get an error if you try to run `terraform plan`.  You will need to re-run `terraform init` in that directory.  This should be added to the solutions area

```shell
Error: provider.random: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
```

**Comment by gfilicetti** [comment]
Tommy..... who is the owner of this hack? Let's ping him/her directly and point them to your issue here.

**Comment by lastcoolnameleft** [comment]
Looks like @perktime authored the docs.  That said, this was from a long time ago, so I don't know the current status for this issue.

**Comment by gfilicetti** [comment]
@perktime has fixed this donkey's years ago
