### ISSUE TITLE
[Proposal]: Build out the Bronze-Silver-Gold Architecture Using Data Lake, Delta Technology, Synapse and Databricks

### ISSUE THREAD

**Issue by jcbendernh** [microsoft/WhatTheHack#523]
### Topic

The purpose of this hackathon is to showcase how to build out a Bronze-Silver-Gold architecture by combining two different data sources and standardizing them in a Delta Lake format utilizing Synapse and Databricks and then serving them in a Gold/Curated Layer for dashboard and reporting purposes. 

### Abstract/Learning Objectives

Upon completion of this Hack, you will be able to perform the following...

1. Land external data in a Bronze/Raw layer.
2. Combine disparate data sources in a Silver/Integrated layer residing in Delta format.
3. Create a Gold/Curated layer to aggregate data and apply row level security
4. Surface the combined data in reports and dashboards

### Delivery Date

12/2/22 - 12/16/22 (3 half day sessions)

### Authors

```markdown
jcbendernh & FarhanArif
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrzyshr** [comment]
This issue should be closed by PR #559
