### ISSUE TITLE
[Proposal]: Entra ID and Entra B2B

### ISSUE THREAD

**Issue by bappadityams** [microsoft/WhatTheHack#565]
### Topic

Create an Azure Active Directory Tenant
Register an application with Azure Active Directory
Invite a guest user to an Azure Active Directory tenant
Integrate Azure Active Directory authentication into an Azure App Service using App Service Authentication (EasyAuth)
Understand how to integrate Azure Active Directory authentication into an application (ASP.Net / SPA / Desktop, etc.) via code.
Deploy your Azure Active Directory authenticated application to Azure

### Abstract/Learning Objectives

In this what the hack, participants will learn what Azure Active Directory (AAD) is and how to use this service to implement modern authentication in their applications.

This hack is useful for identity architects and developers who want to integrate their solutions with the Microsoft Identity Platform to allow organizational users as well as external identities to sign into their custom developed applications.

### Delivery Date

1/20/2023

### Authors

```markdown
Bappaditya Banerjee(https://github.com/bappadityams)
Nick McCollum(https://github.com/nimccoll)
```

### Other

We are ready with the content and the PR. We already conducted the hack within FTA App Dev team.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrzyshr** [comment]
PR #683 should close this.
