### ISSUE TITLE
[Report]: TrafficControlWithDapr at Confluent

### ISSUE THREAD

**Issue by jordanbean-msft** [microsoft/WhatTheHack#601]
### Which Hack did you host?

047-TrafficControlWithDapr

### Event Date

04/10/2023

### Organization, Audience and Location

Confluent, 15 developers, virtual

### Coaches and Team

@jordanbean-msft
@bcheng-ms

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrzyshr** [comment]
Thx for sharing.
