### ISSUE TITLE
[Proposal]: OpenAI Fundamentals

### ISSUE THREAD

**Issue by izzymsft** [microsoft/WhatTheHack#624]
### Topic

The objective of this hack is to cover basic and fundamental scenarios for leveraging OpenAI capabilities on Microsoft Azure.

### Abstract/Learning Objectives

To enable participants understand how to use the different OpenAI offerings available on Azure.

### Delivery Date

2023/06/15

### Authors

```markdown
- [Israel Ekpo](https://github.com/izzymsft)
- [Ellie Nosrat](https://github.com/ellienosrat)
- [Shiva Chittamuru](https://github.com/shivachittamuru)
- [Mike Richter](https://github.com/michaelsrichter)
- [Sowmyan Soman Chullikkattil](https://github.com/sowsan)
- [Amanda Wong](https://github.com/wongamanda)
- [Devanshi Thakar](https://github.com/devanshithakar12)
- [Alexis Joseph](https://github.com/alexistj)
- [Melody Yin](https://github.com/melody-N07)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrzyshr** [comment]
PR #690 should close this issue

**Comment by jrzyshr** [comment]
Congrats to the team on publishing the OpenAI Fundamentals hack!
